my_string=input('8-800-555-35-35 - проще позвонить, чем ')
print(len(my_string))
print(my_string .upper())
print(my_string .lower())
print(my_string .replace(' ', ''))
print(my_string[0])
print(my_string[-1])